spring:
  application:
    name: api-invoice-sender
  flyway:
    enabled: true
    group: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

# OpenAPI
openapi:
  name: invoice-sender
  title: InvoiceSender
  version: '@project.version@'

logbook:
  body-filters:
    # Exclude BASE64-encoded content from requests.
    jsonPath:
      - key: '$.files[*].content'
        value : '[base64]'
