spring:
  application:
    name: api-invoice-sender
  flyway:
    enabled: true
    group: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

# OpenAPI
openapi:
  name: invoice-sender
  title: InvoiceSender
  version: '@project.version@'

invoice-processor:
  schedule:
    municipality-ids:
      - 2281
logbook:
  body-filters:
    # Exclude BASE64-encoded content from requests.
    jsonPath:
      - key: '$.files[*].content'
        value: '[base64]'

# Ignore ClientProblem exceptions in circuitbreaker.
# There are cases where a 4xx response is normal behaviour and should not open the circuitbreaker.
resilience4j.circuitbreaker:
  instances:
    Messaging:
      ignore-exceptions:
        - se.sundsvall.dept44.exception.ClientProblem

scheduler:
  move-files:
    name: writeAndArchiveBatch
    # Every 5 minutes between 03:00-08:00 Monday-Friday
    cron: '* */5 3-8 ? * MON-FRI'
  shedlock-lock-at-most-for: PT2M
  maximum-execution-time: PT2M


